### ISSUE TITLE
CodaLab : input_rel_path issue

### ISSUE THREAD

**Issue by DongWan0285** [PRBonn/semantic-kitti-api#52] opened 2020-07-16 07:35 UTC
Hello Im DongWan

I summit the lable for SemanticKITTI: Semantic Segmentation

but I take the error

Can you help this

I don't know what's the reason

Traceback (most recent call last):
File "/worker/worker.py", line 330, in run
if input_rel_path not in bundles:
TypeError: argument of type 'NoneType' is not iterable

**Comment by mgerdzhev** [comment] 2020-07-20 19:49
hey @DongWan0285 did you manage to solve the issue? I am getting the same one today.

**Comment by jbehley** [comment] 2020-07-20 20:02
It might be an issue with the server that was resolved earlier. Please try again tomorrow and let me know if the issue persists. 

Sometimes its also an issue with Azure that cannot be resolved by codalab.

**Comment by mgerdzhev** [comment] 2020-07-20 20:06
It was my second submission for the day. My first one went through no problem, then the second one - 20 minutes later got this error. I will retry it again tomorrow, hopefully it works.

**Comment by DongWan0285** [comment] 2020-07-21 05:40
> 헤이 @ DongWan0285는 당신이 문제를 해결하기 위해 관리나요? 나는 오늘 같은 것을 얻고있다.

I still have problem.

but In my case It have a rule 1 day 1 test no errors.
First test after still have problem
so I used 1day 1 test haha

**Comment by MukundVarmaT** [comment] 2020-07-29 06:12
Are you all facing this issue still? Cause I just ran into it while making a submission today. Is it an issue with the submission file or with the server itself because I did see it mentioned on the competition pages like this [one](https://competitions.codalab.org/competitions/24942)

**Comment by jbehley** [comment] 2020-07-29 10:25
I didn't get an answer from the Codalab team. The issue is still happening. If you get this error, you can try to resubmit, since other people get still results. It might be that only some instances are affected.

I keep you updated.

**Comment by MukundVarmaT** [comment] 2020-07-30 09:33
I think the issue is resolved right now and I was able to submit it. Thank you.

**Comment by dante0shy** [comment] 2020-08-05 09:25
Hi, Sir. I've got the same problem with my submission. I try two times, and both of them returned this problem. Do you guys have any solution?

**Comment by jbehley** [comment] 2020-08-29 18:40
it seems to be resolved. Please reopen the issue if you experience this issue again.

**Closed by jbehley** 2020-08-29 18:40 UTC
